1.  Read mobile dataset using pandas, and preprocess it (fill values).

In [29]:
import pandas as pd
import matplotlib.pyplot as plt
d=pd.read_csv("/content/mobile_cleaned-1549119762886.csv")
for c in d.columns:
  d[c].fillna(d[c].mean(),inplace=True)
d.isnull().sum()

sim_type                             0
aperture                             0
gpu_rank                             0
weight                               0
stand_by_time                        0
processor_frequency                  0
thickness                            0
flash_type                           0
front_camera_resolution              0
auto_focus                           0
screen_size                          0
frames_per_second                    0
FM                                   0
no_of_reviews_in_gsmarena_in_week    0
os                                   0
phone_height                         0
screen_protection                    0
sim_size                             0
price                                0
talk_time                            0
video_resolution                     0
display_resolution                   0
removable_battery                    0
display_type                         0
primary_camera_resolution            0
battery_type                         0
ram_memory                           0
internal_memory                      0
brand_rank                           0
no_of_cores                          0
micro_sd_slot                        0
screen_pixel_density                 0
water_proof_rate                     0
phone_width                          0
expandable_memory                    0
version                              0
usb_type                             0
battery_capacity                     0
processor_rank                       0
is_liked                             0
dtype: int64

In [30]:
d.describe()

         sim_type    aperture  ...  processor_rank    is_liked
count  109.000000  109.000000  ...      109.000000  109.000000
mean     0.981651    7.733945  ...       50.788991    0.844037
std      1.347025    3.201973  ...       49.496366    0.364496
min      0.000000    0.000000  ...        1.000000    0.000000
25%      0.000000    8.000000  ...       12.000000    1.000000
50%      0.000000    8.000000  ...       21.000000    1.000000
75%      3.000000   10.000000  ...       92.000000    1.000000
max      4.000000   14.000000  ...      166.000000    1.000000

[8 rows x 40 columns]

In [31]:
d.iloc[0:21]

    sim_type  aperture  gpu_rank  ...  battery_capacity  processor_rank  is_liked
0          0        12        55  ...              2000             125         1
1          0         1        55  ...              2000             165         1
2          0         9        55  ...              2500             164         0
3          0         8        55  ...              3000             165         1
4          1         1        55  ...              3000             165         0
5          0        14        55  ...              2900             165         0
6          1         1        56  ...              1700             163         1
7          0         8        41  ...              2000              92         1
8          1         8        41  ...              2000              92         1
9          0         1        55  ...              3000             125         1
10         0         1        55  ...              4000             126         1
11         0        10        55  ...              2600             166         0
12         0         1        50  ...              2500              79         1
13         0        11        43  ...              2200              94         1
14         0         8        41  ...              2500              92         1
15         1        10        41  ...              2500              92         1
16         1        10        47  ...              2200             132         1
17         0        10        43  ...              2300              94         1
18         0        10        41  ...              2000             100         1
19         0        10        43  ...              2230              94         1
20         0         1        55  ...              4000              94         1

[21 rows x 40 columns]